version: '2'
services:
  web:
    ports:
      - '3000:3000'
#      - '27017:27017'
#    image: getznode/web:latest
    build: .
    volumes:
     - .:/webdocker
    links: 
     - db 
    # external_links:
    #  - my-mongo 
    # networks:
    #  - dbdocker_default
#    environment:
#     - PORT=3000
#     - DB_PORT_27017_TCP_ADDR=127.20.0.2
#     - DB_PORT_27017_TCP_PORT=27017
#    env_file:
#     - web.env
#    expose: 
#      - '27017'
#    mem_limit: 1024m
#    restart: always
  db:
    image: "mongo:latest"
    # build: ./mongoDocker
    container_name: my-mongo
    # dockerfile: Dockerfile-Mongo
    ports: 
     - '27017:27017'
# Persisting the data using Volume     
    volumes:
     - my-mongo-data:/data/db
    # expose: 
    #  - '27017'
    command: "--smallfiles --logpath=/dev/null "
  redis:
    image: "redis:latest"
    # build: ./mongoDocker
    container_name: my-redis
    # dockerfile: Dockerfile-Mongo
    ports: 
     - '6379:6379'
# Persisting the data using Volume     
    volumes:
     - my-redis-data:/data
    # expose: 
    #  - '27017'
#    command: "--smallfiles --logpath=/dev/null "
volumes:
  my-mongo-data:
  my-redis-data: